//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta2

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	config "sigs.k8s.io/scheduler-plugins/apis/config"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*RealTimeArgs)(nil), (*config.RealTimeArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RealTimeArgs_To_config_RealTimeArgs(a.(*RealTimeArgs), b.(*config.RealTimeArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.RealTimeArgs)(nil), (*RealTimeArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_RealTimeArgs_To_v1beta2_RealTimeArgs(a.(*config.RealTimeArgs), b.(*RealTimeArgs), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta2_RealTimeArgs_To_config_RealTimeArgs(in *RealTimeArgs, out *config.RealTimeArgs, s conversion.Scope) error {
	return nil
}

// Convert_v1beta2_RealTimeArgs_To_config_RealTimeArgs is an autogenerated conversion function.
func Convert_v1beta2_RealTimeArgs_To_config_RealTimeArgs(in *RealTimeArgs, out *config.RealTimeArgs, s conversion.Scope) error {
	return autoConvert_v1beta2_RealTimeArgs_To_config_RealTimeArgs(in, out, s)
}

func autoConvert_config_RealTimeArgs_To_v1beta2_RealTimeArgs(in *config.RealTimeArgs, out *RealTimeArgs, s conversion.Scope) error {
	return nil
}

// Convert_config_RealTimeArgs_To_v1beta2_RealTimeArgs is an autogenerated conversion function.
func Convert_config_RealTimeArgs_To_v1beta2_RealTimeArgs(in *config.RealTimeArgs, out *RealTimeArgs, s conversion.Scope) error {
	return autoConvert_config_RealTimeArgs_To_v1beta2_RealTimeArgs(in, out, s)
}
