apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.controller.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.scheduler.name }}
  namespace: {{ .Values.scheduler.namespace }}
secrets:
- name: gitlab-rt-tests
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.controller.namespace }}
secrets:
- name: gitlab-rt-tests
