
# Default values for scheduler-plugins-as-a-second-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  name: scheduler-plugins-scheduler
  image: registry.gitlab.com/francescol96/rt-tests-container/kube-scheduler:v0.22.6
  namespace: scheduler-plugins
  replicaCount: 1

controller:
  name: scheduler-plugins-controller
  image: registry.gitlab.com/francescol96/rt-tests-container/controller:v0.22.6
  namespace: scheduler-plugins
  replicaCount: 1

# LoadVariationRiskBalancing and TargetLoadPacking are not enabled by default
# as they need extra RBAC privileges on metrics.k8s.io.

plugins:
  enabled: ["RealTime"]

global:  
   # queueSort is not indented under extensions 
   # as it needs to be globally enabled once. 
  queueSort: ["RealTime"]
  extensions: 
    filter: ["RealTime"] 
    score: ["RealTime"] 
